from pages.why_georgia_page import WhyGeorgiaPage
from utils.DriverUtils import DriverUtils


class WhyGeorgiaSteps:
    @staticmethod
    def why_georgia_steps():
        why_georgia_page = WhyGeorgiaPage()
        why_georgia_page.click_why_georgia()
        why_georgia_page.is_visible()
        why_georgia_page.click_left_bar_1()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_batumi()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_qutaisi()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_tbilisi()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_2()
        why_georgia_page.click_summer()
        why_georgia_page.click_spring()
        why_georgia_page.click_winter()
        why_georgia_page.click_fall()
        why_georgia_page.click_season_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_3()
        why_georgia_page.click_wine_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_4()
        why_georgia_page.click_alphabet_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_5()
        why_georgia_page.click_kitchen_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_6()
        why_georgia_page.click_music_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_7()
        why_georgia_page.click_dance_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_8()
        why_georgia_page.click_how_is_georgia()
        why_georgia_page.click_left_bar_9()
        why_georgia_page.click_history_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_10()
        why_georgia_page.click_civilisation_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_11()
        why_georgia_page.click_highest_learn_more()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_12()
        why_georgia_page.click_travel_to_georgia()
