from pages.main_page import MainPage
from pages.why_georgia_page import WhyGeorgiaPage
from utils.DriverUtils import DriverUtils


class WhyGeorgiaSteps:
    @staticmethod
    def why_georgia_steps():
        main_page = MainPage()
        why_georgia_page = WhyGeorgiaPage()
        why_georgia_page.click_why_georgia()
        why_georgia_page.is_visible()
        why_georgia_page.click_left_bar_1()
        main_page.close_ri_line()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_batumi()
        why_georgia_page.batumi_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_qutaisi()
        why_georgia_page.qutaisi_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities()
        why_georgia_page.click_tbilisi()
        why_georgia_page.tbilisi_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_main_cities_learn_more()
        why_georgia_page.geography_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_2()
        why_georgia_page.visible_summer()
        why_georgia_page.visible_spring()
        why_georgia_page.visible_winter()
        why_georgia_page.visible_fall()
        why_georgia_page.click_season_learn_more()
        why_georgia_page.seasons_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_3()
        why_georgia_page.click_wine_learn_more()
        why_georgia_page.wine_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_4()
        why_georgia_page.click_alphabet_learn_more()
        why_georgia_page.alphabet_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_5()
        why_georgia_page.click_kitchen_learn_more()
        why_georgia_page.kitchen_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_6()
        why_georgia_page.click_music_learn_more()
        why_georgia_page.music_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_7()
        why_georgia_page.click_dance_learn_more()
        why_georgia_page.dance_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_8()
        why_georgia_page.click_how_is_georgia()
        why_georgia_page.click_left_bar_9()
        why_georgia_page.click_history_learn_more()
        why_georgia_page.history_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_10()
        why_georgia_page.click_civilisation_learn_more()
        why_georgia_page.civilisation_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_11()
        why_georgia_page.click_highest_learn_more()
        why_georgia_page.highest_is_visible()
        DriverUtils.go_back()
        why_georgia_page.click_left_bar_12()
        why_georgia_page.click_travel_to_georgia()
        why_georgia_page.travel_is_visible()

